version: '2'

networks:
  ccb:
    driver: bridge
  ual:
    external:
      name: ual_default

services:

# Wordpress
  ccb:
    build: .
    depends_on:
      - mysql
    networks:
      - ual
      - ccb
    external_links:
      - gpoauth:gpoauth
      - gpidm:gpidm
    links:
      - mysql:mysql
    ports:
      - "80:80"
      - "81:80"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins:rw
      - ./themes:/var/www/html/wp-content/themes:rw
      - ./uploads:/var/www/html/wp-content/uploads:rw
    environment:
      # Site specifics
      root_url: http://localhost
      sitename: my-test-site
      # URLs
      maps_url: https://maps.geoplatform.gov
      viewer_url: https://viewer.geoplatform.gov
      marketplace_url: https://marketplace.geoplatform.gov
      dashboard_url: https://dashboard.geoplatform.gov/
      wpp_url: https://www.geoplatform.gov
      ual_url: https://ual.geoplatform.gov
      ckan_mp_url: https://marketplace.geoplatform.gov/
      ckan_url: https://data.geoplatform.gov/
      cms_url: https://www.geoplatform.gov/geoplatform-resources/
      idp_url: https://idp.geoplatform.gov
      oe_url: https://oe.geoplatform.gov
      accounts_url: https://accounts.geoplatform.gov
      comm_url: https://www.geoplatform.gov/communities
      rpm_url: https://rpm.geoplatform.gov
      rpm_token: 47d10365bff7ac8d86a96bd4537b2891
      sd_url: servicedesk@geoplatform.gov
      ga_code: UA-42040723-1
      rep_org: My Test Site
      # Datebase
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: imroot:012!

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - ccb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: imroot:012!
    volumes:
       - /var/lib/mysql

  phpadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - "8888:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: imroot:012!


  ########## Oauth Stack ##########

  # gpoauth:
  #   image: 046725759240.dkr.ecr.us-east-1.amazonaws.com/gpoauth:latest
  #   ports:
  #     - "8889:8889"
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo:mongo
  #   environment:
  #     NODE_ENV: sit
  #     DB_HOST: mongo
  #     appSecret: 0123456789QWERTY
  #     jwtLifetime: 10s
  #     refreshLifetime: 1
  #   restart: always

  # gpidm:
  #   image: 046725759240.dkr.ecr.us-east-1.amazonaws.com/oauthidm:latest
  #   ports:
  #     - "8443:80"
  #   depends_on:
  #     - gpoauth
  #   environment:
  #     NODE_ENV: local
  #     IDP_BASE_URL: "http://localhost:8889"
  #     CALLBACK: "http://localhost:8443/#"
  #     AUTH_TYPE: "token"
  #     APP_ID: "5a56aaeca9e0221520f413a9"
  #     PORTAL_URL: "http://localhost"
  #     FORCE_LOGIN: "true"
  #     LOGIN_URL: "/#/login"
  #     LOGOUT_URL: "/#/login"
  #   restart: always

  # mongo:
  #   image: mongo:3.2
  #   ports:
  #     - "27017:27017"
  #     - "28017:28017"
  #   restart: always
