version: '2'
services:

# Wordpress
  ccb:
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "80:80"
      - "81:80"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins:rw
      - ./themes:/var/www/html/wp-content/themes:rw
    environment:
      # Site specifics
      root_url: http://localhost
      sitename: my-test-site
      # Datebase
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: imroot:012!

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: imroot:012!
    volumes:
       - /var/lib/mysql

  phpadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - "8888:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: imroot:012!
