version: '2'
services:

# CCB
  ccb:
    build: .
    ports:
     - "80:80"
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf:rw
#     - ./plugins:/usr/share/nginx/html/wp-content/plugins:rw
     - ./themes:/usr/share/nginx/html/wp-content/themes:rw
     - ./uploads:/usr/share/nginx/html/wp-content/uploads:rw
    networks:
     - code-network
    environment:
      # Datebase
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: imroot:012!

# MYSQL
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: imroot:012!
    volumes:
       - /db-data:/var/lib/mysql
    networks:
     - code-network

networks:
  code-network:
    driver: bridge

# NGINX
#   nginx:
# #    build: .
#     image: nginx:latest

#     volumes:
#      - ./html:/var/www/html:rw
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#     networks:
#      - code-network

# Wordpress with FPN
#   wp_php:
#     build: .
# #    image: wordpress:php7.2-fpm
#     volumes:
#      - ./html:/var/www/html:rw
#     networks:
#      - code-network
#     environment:
#       # Datebase
#       WORDPRESS_DB_NAME: wordpress
#       WORDPRESS_TABLE_PREFIX: wp_
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: imroot:012!


  # phpadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #    - mysql
  #   links:
  #    - mysql:db
  #   ports:
  #    - "8888:80"
  #   environment:
  #     PMA_USER: root
  #     PMA_PASSWORD: imroot:012!



# Wordpress
#  ccb:
#    build: .
#    depends_on:
#      - mysql
#    links:
#      - mysql:mysql
#    ports:
#      - "80:80"
#      - "81:80"
#    volumes:
#      - ./plugins:/var/www/html/wp-content/plugins:rw
#      - ./themes:/var/www/html/wp-content/themes:rw
#      - ./uploads:/var/www/html/wp-content/uploads:rw
#    environment:
#      # Site specifics
#      root_url: http://localhost
#      sitename: my-test-site
#      # URLs
#      maps_url: https://maps.geoplatform.gov
#      viewer_url: https://viewer.geoplatform.gov
#      marketplace_url: https://marketplace.geoplatform.gov
#      dashboard_url: https://dashboard.geoplatform.gov/
#      wpp_url: https://www.geoplatform.gov
#      ual_url: https://ual.geoplatform.gov
#      ckan_mp_url: https://marketplace.geoplatform.gov/
#      ckan_url: https://data.geoplatform.gov/
#      cms_url: https://www.geoplatform.gov/geoplatform-resources/
#      idp_url: https://idp.geoplatform.gov
#      oe_url: https://oe.geoplatform.gov
#      accounts_url: https://accounts.geoplatform.gov
#      comm_url: https://www.geoplatform.gov/communities
#      sd_url: servicedesk@geoplatform.gov
#      ga_code: UA-42040723-1
#      # Datebase
#      WORDPRESS_DB_NAME: wordpress
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: imroot:012!
