version: '2'
services:

# Wordpress
  ccb:
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "80:80"
      - "81:80"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins:rw
      - ./themes:/var/www/html/wp-content/themes:rw
    environment:
      # Site specifics
      root_url: http://localhost
      maps_url: https://sit-maps.geoplatform.us
      viewer_url: https://sit-viewer.geoplatform.us
      marketplace_url: https://sit-marketplace.geoplatform.us
      dashboard_url: https://sit-dashboard.geoplatform.us/#/lma?surveyId=8&page=0&size=500&sortElement=title&sortOrder=asc&colorTheme=green
      wpp_url: https://sit-geoplatform.us
      ual_url: https://sit-ual.geoplatform.us
      ckan_mp_url: https://sit-ckan.geoplatform.us/#/?progress=planned&h=Marketplace
      ckan_url: https://sit-ckan.geoplatform.us/
      cms_url: https://sit-cms.geoplatform.us/resources
      idp_url: https://sit-idp.geoplatform.us
      oe_url: https://sit-oe.geoplatform.us
      sd_url: servicedesk@geoplatform.us
      ga_code: UA-42040723-1

      # Datebase
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: imroot:012!

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: imroot:012!
    volumes:
       - /var/lib/mysql
